const products = [
    {
        id: 1,
        name: "Classic Aviator Sunglasses",
        price: 25.99,
        originalPrice: 35.99,
        category: "sunglasses",
        image: "images/sunglasses1.jpg",
        rating: 4,
        description: "These classic aviator sunglasses feature UV400 protection lenses and a lightweight metal frame for all-day comfort.",
        colors: ["Black", "Gold", "Silver"],
        inStock: true
    },
    {
        id: 2,
        name: "Floral Eau de Parfum",
        price: 39.99,
        originalPrice: 49.99,
        category: "perfumes",
        image: "images/perfume1.jpg",
        rating: 5,
        description: "A delicate floral fragrance with notes of jasmine, rose, and vanilla. Long-lasting scent perfect for everyday wear.",
        sizes: ["30ml", "50ml", "100ml"],
        inStock: true
    },
    {
        id: 3,
        name: "Hydrating Moisturizing Cream",
        price: 15.99,
        originalPrice: 19.99,
        category: "creams",
        image: "images/cream1.jpg",
        rating: 4,
        description: "Deeply hydrating cream with hyaluronic acid and vitamin E. Suitable for all skin types, non-greasy formula.",
        skinType: ["Dry", "Normal", "Combination"],
        inStock: true
    },
    {
        id: 4,
        name: "Girls' Summer Floral Dress",
        price: 29.99,
        originalPrice: 39.99,
        category: "girls-fashion",
        image: "images/dress1.jpg",
        rating: 5,
        description: "Lightweight cotton dress with beautiful floral print. Perfect for summer days and special occasions.",
        sizes: ["2-4 Years", "4-6 Years", "6-8 Years"],
        inStock: true
    },
    {
        id: 5,
        name: "Round Retro Sunglasses",
        price: 22.99,
        originalPrice: 29.99,
        category: "sunglasses",
        image: "images/sunglasses2.jpg",
        rating: 4,
        description: "Vintage-inspired round sunglasses with UV protection lenses. Comes with a protective case.",
        colors: ["Tortoise", "Black", "Red"],
        inStock: true
    },
    {
        id: 6,
        name: "Citrus Fresh Cologne",
        price: 34.99,
        originalPrice: 44.99,
        category: "perfumes",
        image: "images/perfume2.jpg",
        rating: 4,
        description: "Fresh and energizing citrus fragrance with notes of bergamot, lemon, and cedarwood.",
        sizes: ["50ml", "100ml"],
        inStock: true
    },
    {
        id: 7,
        name: "Anti-Aging Night Cream",
        price: 24.99,
        originalPrice: 29.99,
        category: "creams",
        image: "images/cream2.jpg",
        rating: 5,
        description: "Rich night cream with retinol and peptides to reduce fine lines and wrinkles while you sleep.",
        skinType: ["Mature", "Dry", "Normal"],
        inStock: true
    },
    {
        id: 8,
        name: "Girls' Denim Jacket",
        price: 35.99,
        originalPrice: 45.99,
        category: "girls-fashion",
        image: "images/jacket1.jpg",
        rating: 4,
        description: "Classic denim jacket with adjustable cuffs and fun embroidery details. Machine washable.",
        sizes: ["3-4 Years", "5-6 Years", "7-8 Years"],
        inStock: true
    },
    {
        id: 9,
        name: "Cat Eye Sunglasses",
        price: 27.99,
        originalPrice: 34.99,
        category: "sunglasses",
        image: "images/sunglasses3.jpg",
        rating: 5,
        description: "Elegant cat eye sunglasses with polarized lenses and rhinestone accents on the temples.",
        colors: ["Black", "Tortoise", "Pink"],
        inStock: true
    },
    {
        id: 10,
        name: "Woody Oriental Perfume",
        price: 45.99,
        originalPrice: 55.99,
        category: "perfumes",
        image: "images/perfume3.jpg",
        rating: 4,
        description: "Warm and sensual fragrance with notes of sandalwood, amber, and vanilla. Perfect for evening wear.",
        sizes: ["50ml", "100ml"],
        inStock: true
    },
    {
        id: 11,
        name: "Brightening Day Cream",
        price: 19.99,
        originalPrice: 24.99,
        category: "creams",
        image: "images/cream3.jpg",
        rating: 4,
        description: "Lightweight day cream with vitamin C to brighten skin tone and protect against environmental stressors.",
        skinType: ["Dull", "Normal", "Combination"],
        inStock: true
    },
    {
        id: 12,
        name: "Girls' Tutu Skirt Set",
        price: 32.99,
        originalPrice: 39.99,
        category: "girls-fashion",
        image: "images/skirt1.jpg",
        rating: 5,
        description: "Adorable tutu skirt with matching top. Soft tulle fabric with elastic waistband for comfort.",
        sizes: ["2-3 Years", "4-5 Years", "6-7 Years"],
        inStock: true
    }
];